version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    image: elasticsearch:7.10.1
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  kibana:
    image: kibana:7.10.1
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601